version: '3'

services:

  bot:
    container_name: anketabot
    image: bot-questionnaire:0.0.1v
    build: ./bot
    restart: always
    environment:
      MYSQL_HOST: db
    env_file:
      - .env
    depends_on:
      - db-quests
  db-quests:
    image: mysql:latest
    container_name: db-quests
    restart: always
    ports:
      - "3308:3308"
    command: --port=3308
    environment:
      MYSQL_HOST: '%'
    env_file:
      - .env
