name: builder

on:
  push:
    branches: [ "prod" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy on production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          password: ${{ secrets.DEPLOY_SSH_SECRET }}
          script: |
            cd ${{ github.event.repository.name }}/src
            git pull && git checkout prod
            echo ${{ secrets.DEPLOY_SSH_SECRET }} | sudo -S -k docker-compose up -d --build     
